#!/usr/bin/env python3
"""Tkinter host application for the motorized catheter accumulator.

Position is estimated from step pulses generated by the Arduino. The system has
no encoder, home sensor, or physical limit switch. The Arduino starts in the
UNCALIBRATED state after every reset. Jog to the mechanical zero position and
then select "Set Current Position = 0." Python and Arduino both enforce the
0-280 mm software travel range.
"""

from __future__ import annotations

import math
import queue
import threading
import time
import tkinter as tk
from datetime import datetime
from tkinter import messagebox, scrolledtext, ttk
from typing import Optional

try:
    import serial
    from serial.tools import list_ports
except ImportError:  # Let the GUI show an installation message instead of crashing.
    serial = None
    list_ports = None


BAUD_RATE = 115200
MIN_POSITION_MM = 0.0
MAX_POSITION_MM = 280.0
MIN_SPEED_MM_S = 0.5
MAX_SPEED_MM_S = 15.0
MIN_ACCEL_MM_S2 = 1.0
MAX_ACCEL_MM_S2 = 100.0
DEFAULT_SPEED_MM_S = 5.0
DEFAULT_ACCEL_MM_S2 = 20.0
DEFAULT_DISTANCE_MM = 10.0
HEARTBEAT_MS = 250

# Modern industrial light theme. Status colors communicate actual state only.
COLOR_BACKGROUND = "#EEF1F4"
COLOR_PANEL = "#FFFFFF"
COLOR_BORDER = "#C8D0D8"
COLOR_TITLE = "#203040"
COLOR_PRIMARY = "#286090"
COLOR_PRIMARY_ACTIVE = "#1F4D75"
COLOR_CONNECTED = "#2E7D32"
COLOR_WARNING = "#F9A825"
COLOR_DANGER = "#C62828"
COLOR_DANGER_ACTIVE = "#8E0000"
COLOR_TEXT = "#202830"
COLOR_SECONDARY_TEXT = "#606C78"
COLOR_DISABLED_BACKGROUND = "#E4E8EC"
COLOR_DISABLED_TEXT = "#9AA3AC"


class SerialController:
    """Discover serial ports and provide background reads and thread-safe writes."""

    PREFERRED_PORT_WORDS = (
        "arduino",
        "usb serial",
        "usb-serial",
        "ch340",
        "ch341",
        "usbmodem",
        "usbserial",
    )

    def __init__(self, event_queue: queue.Queue):
        self.events = event_queue
        self._serial = None
        self._reader_thread: Optional[threading.Thread] = None
        self._connector_thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._write_lock = threading.Lock()
        self._state_lock = threading.Lock()
        self._manual_close = False

    @property
    def is_open(self) -> bool:
        with self._state_lock:
            return bool(self._serial and self._serial.is_open)

    @staticmethod
    def discover_ports():
        if list_ports is None:
            return []
        return sorted(list(list_ports.comports()), key=lambda item: item.device)

    @classmethod
    def preferred_port(cls, ports):
        for port in ports:
            searchable = f"{port.device} {port.description} {port.manufacturer or ''}".lower()
            if any(word in searchable for word in cls.PREFERRED_PORT_WORDS):
                return port.device
        return ports[0].device if len(ports) == 1 else None

    def open_async(self, port: str) -> None:
        """Open a serial port asynchronously; the GUI handles the UNO reset delay."""
        if serial is None:
            self.events.put(("OPEN_ERROR", "pyserial is not installed. Run: python -m pip install pyserial"))
            return
        if self.is_open or (self._connector_thread and self._connector_thread.is_alive()):
            return

        self._manual_close = False
        self._stop_event = threading.Event()

        def connector():
            try:
                connection = serial.Serial(
                    port=port,
                    baudrate=BAUD_RATE,
                    timeout=0.10,
                    write_timeout=0.50,
                )
                connection.reset_input_buffer()
                with self._state_lock:
                    self._serial = connection
                self.events.put(("PORT_OPEN", port))
                self._reader_thread = threading.Thread(
                    target=self._reader_loop,
                    args=(connection, self._stop_event),
                    name="serial-reader",
                    daemon=True,
                )
                self._reader_thread.start()
            except Exception as exc:
                self.events.put(("OPEN_ERROR", str(exc)))

        self._connector_thread = threading.Thread(
            target=connector, name="serial-connector", daemon=True
        )
        self._connector_thread.start()

    def _reader_loop(self, connection, stop_event: threading.Event) -> None:
        while not stop_event.is_set():
            try:
                raw = connection.readline()
                if raw:
                    line = raw.decode("ascii", errors="replace").strip()
                    if line:
                        self.events.put(("LINE", line))
            except Exception as exc:
                if not stop_event.is_set() and not self._manual_close:
                    self.events.put(("CONNECTION_LOST", str(exc)))
                break

    def write_line(self, command: str) -> bool:
        """Use one lock for all writers so command bytes cannot interleave."""
        payload = (command.strip() + "\n").encode("ascii")
        try:
            with self._write_lock:
                with self._state_lock:
                    connection = self._serial
                if not connection or not connection.is_open:
                    return False
                connection.write(payload)
            return True
        except Exception as exc:
            self.events.put(("CONNECTION_LOST", str(exc)))
            return False

    def close(self) -> None:
        self._manual_close = True
        self._stop_event.set()
        with self._state_lock:
            connection = self._serial
            self._serial = None
        if connection:
            try:
                connection.close()
            except Exception:
                pass


class LinearStageGUI:
    """Manage the Tkinter UI, validation, protocol parsing, and safety behavior."""

    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("Catheter Accumulator Controller")
        self.root.configure(background=COLOR_BACKGROUND)
        # Use nearly all available screen space while leaving room for the title
        # bar and the macOS menu bar or Dock.
        screen_width = self.root.winfo_screenwidth()
        screen_height = self.root.winfo_screenheight()
        window_width = max(1100, screen_width)
        window_height = max(700, screen_height - 60)
        self.root.geometry(f"{window_width}x{window_height}+0+25")
        self.root.minsize(1100, 700)

        self.events: queue.Queue = queue.Queue()
        self.serial_controller = SerialController(self.events)

        self.connected = False       # True only after receiving PONG.
        self.connecting = False
        self.calibrated = False
        self.current_position: Optional[float] = None
        self.motion_state = "IDLE"
        self.jog_held = False
        self.jog_direction: Optional[str] = None
        self.jog_button = None
        self.jog_stop_pending = False
        self.closing = False
        self.handshake_timeout_id = None

        self.port_var = tk.StringVar()
        self.connection_var = tk.StringVar(value="DISCONNECTED")
        self.calibration_var = tk.StringVar(value="UNCALIBRATED")
        self.position_var = tk.StringVar(value="UNCALIBRATED")
        self.motion_var = tk.StringVar(value="IDLE")
        self.target_var = tk.StringVar(value="--")
        self.commanded_speed_var = tk.StringVar(value=f"{DEFAULT_SPEED_MM_S:.2f} mm/s")
        self.distance_var = tk.StringVar(value=f"{DEFAULT_DISTANCE_MM:.2f}")
        self.speed_var = tk.StringVar(value=f"{DEFAULT_SPEED_MM_S:.2f}")
        self.accel_var = tk.StringVar(value=f"{DEFAULT_ACCEL_MM_S2:.2f}")

        self._build_styles()
        self._build_ui()
        self._refresh_ports(show_message=False)
        self._update_controls()

        self.root.protocol("WM_DELETE_WINDOW", self._on_close)
        self.root.bind("<FocusOut>", self._on_focus_out, add="+")
        self.root.bind_all("<ButtonRelease-1>", self._global_button_release, add="+")
        self.root.after(50, self._process_events)
        self.root.after(HEARTBEAT_MS, self._heartbeat)

        if serial is None:
            self.root.after(
                100,
                lambda: messagebox.showerror(
                    "Missing Dependency",
                    "pyserial is not installed.\n\nRun:\npython -m pip install pyserial",
                ),
            )

    def _build_styles(self) -> None:
        style = ttk.Style()
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass
        # Use cool light gray for the window and white for functional panels.
        style.configure(".", background=COLOR_BACKGROUND, foreground=COLOR_TEXT)
        style.configure("TFrame", background=COLOR_BACKGROUND)
        style.configure("Panel.TFrame", background=COLOR_PANEL)
        style.configure("TLabel", background=COLOR_PANEL, foreground=COLOR_TEXT)
        style.configure(
            "Title.TLabel",
            background=COLOR_BACKGROUND,
            foreground=COLOR_TITLE,
            font=("TkDefaultFont", 18, "bold"),
        )
        style.configure(
            "Section.TLabelframe",
            background=COLOR_PANEL,
            bordercolor=COLOR_BORDER,
            lightcolor=COLOR_BORDER,
            darkcolor=COLOR_BORDER,
            borderwidth=1,
            relief="solid",
        )
        style.configure(
            "Section.TLabelframe.Label",
            background=COLOR_BACKGROUND,
            foreground=COLOR_TITLE,
            font=("TkDefaultFont", 11, "bold"),
        )
        style.configure(
            "Value.TLabel",
            background=COLOR_PANEL,
            foreground=COLOR_TITLE,
            font=("TkDefaultFont", 12, "bold"),
        )
        style.configure(
            "Active.TLabel",
            background=COLOR_PANEL,
            foreground=COLOR_PRIMARY,
            font=("TkDefaultFont", 12, "bold"),
        )
        style.configure(
            "Connected.TLabel",
            background=COLOR_PANEL,
            foreground=COLOR_CONNECTED,
            font=("TkDefaultFont", 12, "bold"),
        )
        style.configure(
            "Warning.TLabel",
            background=COLOR_PANEL,
            foreground=COLOR_WARNING,
            font=("TkDefaultFont", 12, "bold"),
        )
        style.configure(
            "Danger.TLabel",
            background=COLOR_PANEL,
            foreground=COLOR_DANGER,
            font=("TkDefaultFont", 12, "bold"),
        )
        style.configure(
            "Muted.TLabel",
            background=COLOR_PANEL,
            foreground=COLOR_SECONDARY_TEXT,
            font=("TkDefaultFont", 12, "bold"),
        )
        style.configure(
            "Note.TLabel", background=COLOR_PANEL, foreground=COLOR_SECONDARY_TEXT
        )

        # Keep inputs white, use industrial blue for focus, and gray for disabled states.
        style.configure(
            "TEntry",
            fieldbackground=COLOR_PANEL,
            foreground=COLOR_TEXT,
            bordercolor=COLOR_BORDER,
            lightcolor=COLOR_BORDER,
            darkcolor=COLOR_BORDER,
            insertcolor=COLOR_TEXT,
        )
        style.map(
            "TEntry",
            fieldbackground=[("disabled", COLOR_DISABLED_BACKGROUND)],
            foreground=[("disabled", COLOR_DISABLED_TEXT)],
            bordercolor=[("focus", COLOR_PRIMARY)],
            lightcolor=[("focus", COLOR_PRIMARY)],
            darkcolor=[("focus", COLOR_PRIMARY)],
        )
        style.configure(
            "TCombobox",
            fieldbackground=COLOR_PANEL,
            background=COLOR_PANEL,
            foreground=COLOR_TEXT,
            arrowcolor=COLOR_TEXT,
            bordercolor=COLOR_BORDER,
        )
        style.map(
            "TCombobox",
            fieldbackground=[
                ("disabled", COLOR_DISABLED_BACKGROUND),
                ("readonly", COLOR_PANEL),
            ],
            foreground=[("disabled", COLOR_DISABLED_TEXT), ("readonly", COLOR_TEXT)],
            arrowcolor=[("disabled", COLOR_DISABLED_TEXT)],
            bordercolor=[("focus", COLOR_PRIMARY)],
        )

        # Use industrial blue for primary actions and white for secondary tools.
        style.configure(
            "Primary.TButton",
            background=COLOR_PRIMARY,
            foreground=COLOR_PANEL,
            bordercolor=COLOR_PRIMARY,
            lightcolor=COLOR_PRIMARY,
            darkcolor=COLOR_PRIMARY,
            padding=(10, 5),
        )
        style.map(
            "Primary.TButton",
            background=[
                ("disabled", COLOR_DISABLED_BACKGROUND),
                ("pressed", COLOR_PRIMARY_ACTIVE),
                ("active", COLOR_PRIMARY_ACTIVE),
            ],
            foreground=[("disabled", COLOR_DISABLED_TEXT), ("!disabled", COLOR_PANEL)],
            bordercolor=[("disabled", COLOR_BORDER), ("!disabled", COLOR_PRIMARY)],
            lightcolor=[("disabled", COLOR_BORDER), ("!disabled", COLOR_PRIMARY)],
            darkcolor=[("disabled", COLOR_BORDER), ("!disabled", COLOR_PRIMARY)],
        )
        style.configure(
            "Secondary.TButton",
            background=COLOR_PANEL,
            foreground=COLOR_TEXT,
            bordercolor=COLOR_BORDER,
            lightcolor=COLOR_BORDER,
            darkcolor=COLOR_BORDER,
            padding=(10, 5),
        )
        style.map(
            "Secondary.TButton",
            background=[
                ("disabled", COLOR_DISABLED_BACKGROUND),
                ("pressed", COLOR_DISABLED_BACKGROUND),
                ("active", COLOR_BACKGROUND),
            ],
            foreground=[("disabled", COLOR_DISABLED_TEXT), ("!disabled", COLOR_TEXT)],
            bordercolor=[("focus", COLOR_PRIMARY), ("!focus", COLOR_BORDER)],
        )
        style.configure(
            "Danger.TButton",
            background=COLOR_DANGER,
            foreground=COLOR_PANEL,
            bordercolor=COLOR_DANGER,
            lightcolor=COLOR_DANGER,
            darkcolor=COLOR_DANGER,
            font=("TkDefaultFont", 13, "bold"),
            padding=(55, 10),
        )
        style.map(
            "Danger.TButton",
            background=[
                ("disabled", COLOR_DISABLED_BACKGROUND),
                ("pressed", COLOR_DANGER_ACTIVE),
                ("active", COLOR_DANGER_ACTIVE),
            ],
            foreground=[("disabled", COLOR_DISABLED_TEXT), ("!disabled", COLOR_PANEL)],
            bordercolor=[("disabled", COLOR_BORDER), ("!disabled", COLOR_DANGER)],
            lightcolor=[("disabled", COLOR_BORDER), ("!disabled", COLOR_DANGER)],
            darkcolor=[("disabled", COLOR_BORDER), ("!disabled", COLOR_DANGER)],
        )
        style.configure(
            "Close.TButton",
            background=COLOR_PANEL,
            foreground=COLOR_DANGER,
            bordercolor=COLOR_DANGER,
            lightcolor=COLOR_DANGER,
            darkcolor=COLOR_DANGER,
            font=("TkDefaultFont", 10, "bold"),
            padding=(12, 5),
        )
        style.map(
            "Close.TButton",
            background=[("pressed", COLOR_DANGER_ACTIVE), ("active", COLOR_DANGER)],
            foreground=[("pressed", COLOR_PANEL), ("active", COLOR_PANEL)],
        )

    def _build_ui(self) -> None:
        outer = ttk.Frame(self.root, padding=12)
        outer.pack(fill="both", expand=True)

        header = ttk.Frame(outer)
        header.pack(fill="x", pady=(0, 10))
        header.columnconfigure(0, weight=1)
        header.columnconfigure(2, weight=1)
        ttk.Label(header, text="Catheter Accumulator Controller", style="Title.TLabel").grid(
            row=0, column=1
        )
        self.close_button = ttk.Button(
            header,
            text="Close Application",
            command=self._on_close,
            style="Close.TButton",
        )
        self.close_button.grid(row=0, column=2, sticky="e")

        # Two columns use widescreen space: controls on the left and status on the right.
        workspace = ttk.Frame(outer)
        workspace.pack(fill="both", expand=True)
        workspace.columnconfigure(0, weight=1, uniform="main_columns")
        workspace.columnconfigure(1, weight=1, uniform="main_columns")
        workspace.rowconfigure(0, weight=1)

        left_panel = ttk.Frame(workspace)
        left_panel.grid(row=0, column=0, sticky="nsew", padx=(0, 6))
        right_panel = ttk.Frame(workspace)
        right_panel.grid(row=0, column=1, sticky="nsew", padx=(6, 0))

        serial_frame = ttk.LabelFrame(left_panel, text="Serial Connection", style="Section.TLabelframe", padding=10)
        serial_frame.pack(fill="x", pady=4)
        serial_frame.columnconfigure(1, weight=1)
        ttk.Label(serial_frame, text="Port:").grid(row=0, column=0, sticky="w", padx=(0, 8))
        self.port_combo = ttk.Combobox(serial_frame, textvariable=self.port_var, state="readonly")
        self.port_combo.grid(row=0, column=1, sticky="ew", padx=(0, 8))
        self.refresh_button = ttk.Button(
            serial_frame, text="Refresh", command=self._refresh_ports, style="Secondary.TButton"
        )
        self.refresh_button.grid(row=0, column=2, padx=3)
        self.auto_button = ttk.Button(
            serial_frame, text="Auto Detect", command=self._auto_detect, style="Secondary.TButton"
        )
        self.auto_button.grid(row=0, column=3, padx=3)
        self.connect_button = ttk.Button(
            serial_frame, text="Connect", command=self._connect, style="Primary.TButton"
        )
        self.connect_button.grid(row=0, column=4, padx=3)
        self.disconnect_button = ttk.Button(
            serial_frame,
            text="Disconnect",
            command=self._request_disconnect,
            style="Secondary.TButton",
        )
        self.disconnect_button.grid(row=0, column=5, padx=(3, 0))
        ttk.Label(serial_frame, text="Connection:").grid(row=1, column=0, sticky="w", pady=(9, 0))
        self.connection_label = ttk.Label(
            serial_frame, textvariable=self.connection_var, style="Muted.TLabel"
        )
        self.connection_label.grid(row=1, column=1, columnspan=5, sticky="w", pady=(9, 0))

        jog_frame = ttk.LabelFrame(left_panel, text="Manual Jog (Hold to move, release to stop)", style="Section.TLabelframe", padding=10)
        jog_frame.pack(fill="x", pady=4)
        jog_frame.columnconfigure((0, 2), weight=1)
        self.jog_reverse_button = ttk.Button(
            jog_frame, text="◀  Hold Reverse", style="Primary.TButton"
        )
        self.jog_reverse_button.grid(row=0, column=0, sticky="ew", padx=(0, 12), ipady=8)
        self.jog_forward_button = ttk.Button(
            jog_frame, text="Hold Forward  ▶", style="Primary.TButton"
        )
        self.jog_forward_button.grid(row=0, column=2, sticky="ew", padx=(12, 0), ipady=8)
        self.jog_reverse_button.bind(
            "<ButtonPress-1>", lambda event: self._start_jog("REV", event.widget)
        )
        self.jog_forward_button.bind(
            "<ButtonPress-1>", lambda event: self._start_jog("FWD", event.widget)
        )
        self.jog_reverse_button.bind("<ButtonRelease-1>", self._stop_jog)
        self.jog_forward_button.bind("<ButtonRelease-1>", self._stop_jog)
        self.stop_button = ttk.Button(
            jog_frame,
            text="STOP",
            command=self._send_stop,
            style="Danger.TButton",
        )
        self.stop_button.grid(row=1, column=0, columnspan=3, pady=(12, 0))

        move_frame = ttk.LabelFrame(left_panel, text="Fixed Distance Move", style="Section.TLabelframe", padding=10)
        move_frame.pack(fill="x", pady=4)
        move_frame.columnconfigure((0, 1), weight=1)
        distance_row = ttk.Frame(move_frame, style="Panel.TFrame")
        distance_row.grid(row=0, column=0, columnspan=2, pady=(0, 8))
        ttk.Label(distance_row, text="Distance:").pack(side="left")
        self.distance_entry = ttk.Entry(distance_row, textvariable=self.distance_var, width=12)
        self.distance_entry.pack(side="left", padx=8)
        ttk.Label(distance_row, text="mm (enter a positive value)").pack(side="left")
        presets = ttk.Frame(move_frame, style="Panel.TFrame")
        presets.grid(row=1, column=0, columnspan=2, pady=(0, 8))
        self.preset_buttons = []
        for value in (1, 5, 10, 20):
            button = ttk.Button(
                presets,
                text=f"{value} mm",
                command=lambda selected=value: self.distance_var.set(f"{selected:.2f}"),
                width=9,
                style="Secondary.TButton",
            )
            button.pack(side="left", padx=4)
            self.preset_buttons.append(button)
        self.move_reverse_button = ttk.Button(
            move_frame,
            text="← Reverse Move",
            command=lambda: self._move(-1),
            style="Primary.TButton",
        )
        self.move_reverse_button.grid(row=2, column=0, sticky="ew", padx=(0, 8), ipady=5)
        self.move_forward_button = ttk.Button(
            move_frame,
            text="Forward Move →",
            command=lambda: self._move(1),
            style="Primary.TButton",
        )
        self.move_forward_button.grid(row=2, column=1, sticky="ew", padx=(8, 0), ipady=5)

        parameter_frame = ttk.LabelFrame(right_panel, text="Motion Parameters", style="Section.TLabelframe", padding=10)
        parameter_frame.pack(fill="x", pady=4)
        parameter_frame.columnconfigure(1, weight=1)
        ttk.Label(parameter_frame, text="Speed:").grid(row=0, column=0, sticky="w")
        self.speed_entry = ttk.Entry(parameter_frame, textvariable=self.speed_var, width=14)
        self.speed_entry.grid(row=0, column=1, sticky="w", padx=8)
        ttk.Label(parameter_frame, text="mm/s   (0.5–15.0)").grid(row=0, column=2, sticky="w")
        ttk.Label(parameter_frame, text="Acceleration:").grid(row=1, column=0, sticky="w", pady=(8, 0))
        self.accel_entry = ttk.Entry(parameter_frame, textvariable=self.accel_var, width=14)
        self.accel_entry.grid(row=1, column=1, sticky="w", padx=8, pady=(8, 0))
        ttk.Label(parameter_frame, text="mm/s²  (1–100)").grid(row=1, column=2, sticky="w", pady=(8, 0))
        self.apply_button = ttk.Button(
            parameter_frame,
            text="Apply Parameters",
            command=self._apply_parameters,
            style="Primary.TButton",
        )
        self.apply_button.grid(row=0, column=3, rowspan=2, padx=(20, 0), ipadx=8, ipady=5)

        position_frame = ttk.LabelFrame(right_panel, text="Position", style="Section.TLabelframe", padding=10)
        position_frame.pack(fill="x", pady=4)
        position_frame.columnconfigure(1, weight=1)
        ttk.Label(position_frame, text="Calibration:").grid(row=0, column=0, sticky="w")
        self.calibration_label = ttk.Label(
            position_frame, textvariable=self.calibration_var, style="Warning.TLabel"
        )
        self.calibration_label.grid(row=0, column=1, sticky="w")
        ttk.Label(position_frame, text="Current Position:").grid(row=1, column=0, sticky="w", pady=(5, 0))
        ttk.Label(position_frame, textvariable=self.position_var, style="Value.TLabel").grid(row=1, column=1, sticky="w", pady=(5, 0))
        ttk.Label(position_frame, text="Software Range:").grid(row=2, column=0, sticky="w", pady=(5, 0))
        ttk.Label(position_frame, text="0.00 — 280.00 mm").grid(row=2, column=1, sticky="w", pady=(5, 0))
        self.zero_button = ttk.Button(
            position_frame,
            text="Set Current Position = 0",
            command=self._set_zero,
            style="Primary.TButton",
        )
        self.zero_button.grid(row=0, column=2, rowspan=3, padx=(20, 0), ipadx=10, ipady=8)
        ttk.Label(
            position_frame,
            text="Position is estimated from generated step pulses; there is no encoder feedback. Re-zero after power loss or reset.",
            style="Note.TLabel",
        ).grid(row=3, column=0, columnspan=3, sticky="w", pady=(9, 0))

        status_frame = ttk.LabelFrame(right_panel, text="Motion Status", style="Section.TLabelframe", padding=10)
        status_frame.pack(fill="x", pady=4)
        for column in range(6):
            status_frame.columnconfigure(column, weight=1)
        ttk.Label(status_frame, text="State:").grid(row=0, column=0, sticky="e")
        self.motion_status_label = ttk.Label(
            status_frame, textvariable=self.motion_var, style="Value.TLabel"
        )
        self.motion_status_label.grid(row=0, column=1, sticky="w", padx=(5, 12))
        ttk.Label(status_frame, text="Target:").grid(row=0, column=2, sticky="e")
        ttk.Label(status_frame, textvariable=self.target_var, style="Value.TLabel").grid(row=0, column=3, sticky="w", padx=(5, 12))
        ttk.Label(status_frame, text="Speed:").grid(row=0, column=4, sticky="e")
        ttk.Label(status_frame, textvariable=self.commanded_speed_var, style="Value.TLabel").grid(row=0, column=5, sticky="w", padx=(5, 0))

        log_frame = ttk.LabelFrame(right_panel, text="Communication Log", style="Section.TLabelframe", padding=8)
        log_frame.pack(fill="both", expand=True, pady=(4, 0))
        self.log_text = scrolledtext.ScrolledText(
            log_frame,
            height=12,
            state="disabled",
            wrap="word",
            font=("TkFixedFont", 10),
            background=COLOR_PANEL,
            foreground=COLOR_TEXT,
            insertbackground=COLOR_TEXT,
            selectbackground=COLOR_PRIMARY,
            selectforeground=COLOR_PANEL,
            relief="solid",
            borderwidth=1,
            highlightthickness=1,
            highlightbackground=COLOR_BORDER,
            highlightcolor=COLOR_PRIMARY,
        )
        self.log_text.pack(fill="both", expand=True)
        ttk.Button(
            log_frame,
            text="Clear Log",
            command=self._clear_log,
            style="Secondary.TButton",
        ).pack(anchor="e", pady=(5, 0))

    def _log(self, text: str) -> None:
        timestamp = datetime.now().strftime("%H:%M:%S")
        self.log_text.configure(state="normal")
        self.log_text.insert("end", f"[{timestamp}] {text}\n")
        self.log_text.see("end")
        self.log_text.configure(state="disabled")

    def _clear_log(self) -> None:
        self.log_text.configure(state="normal")
        self.log_text.delete("1.0", "end")
        self.log_text.configure(state="disabled")

    def _refresh_ports(self, show_message: bool = True) -> None:
        ports = self.serial_controller.discover_ports()
        devices = [port.device for port in ports]
        self.port_combo["values"] = devices
        if self.port_var.get() not in devices:
            preferred = self.serial_controller.preferred_port(ports)
            self.port_var.set(preferred or (devices[0] if devices else ""))
        self._log(f"Detected ports: {', '.join(devices) if devices else 'none'}")
        if show_message and not devices:
            messagebox.showwarning(
                "No Serial Port",
                "No serial ports were found. Check the USB connection and driver, then try again.",
            )

    def _auto_detect(self) -> None:
        ports = self.serial_controller.discover_ports()
        selected = self.serial_controller.preferred_port(ports)
        if not selected:
            messagebox.showwarning(
                "Auto Detection Failed",
                "No definite Arduino/USB serial port was found. Refresh the list and select a port manually.",
            )
            return
        self.port_combo["values"] = [port.device for port in ports]
        self.port_var.set(selected)
        self._log(f"Auto-detected port: {selected}")
        self._connect()

    def _connect(self) -> None:
        if self.connecting or self.connected or self.serial_controller.is_open:
            return
        port = self.port_var.get().strip()
        if not port:
            messagebox.showwarning(
                "Select a Serial Port", "Refresh the list and select the Arduino port first."
            )
            return
        self.connecting = True
        self.connection_var.set("CONNECTING...")
        self.connection_label.configure(style="Warning.TLabel")
        self._log(f"Opening serial port: {port}")
        self.serial_controller.open_async(port)
        self._update_controls()

    def _begin_handshake(self) -> None:
        if not self.serial_controller.is_open or self.closing:
            return
        self._send_command("PING")
        self._send_command("GET STATUS")
        self.handshake_timeout_id = self.root.after(3000, self._handshake_failed)

    def _handshake_failed(self) -> None:
        self.handshake_timeout_id = None
        if not self.connected and self.serial_controller.is_open:
            messagebox.showerror(
                "Arduino Not Responding",
                "The serial port opened, but no PONG was received. Confirm that this project's firmware is uploaded and the baud rate is 115200, then try again.",
            )
            self._finish_disconnect("Handshake failed; serial port closed")

    def _send_command(self, command: str, log: bool = True) -> bool:
        sent = self.serial_controller.write_line(command)
        if sent and log:
            self._log(f"TX: {command}")
        return sent

    def _request_disconnect(self) -> None:
        if not self.serial_controller.is_open:
            self._finish_disconnect("Disconnected")
            return
        self._clear_jog_hold()
        self._send_command("STOP")
        self.root.after(120, lambda: self._finish_disconnect("Serial port disconnected by user"))

    def _finish_disconnect(self, reason: str) -> None:
        if self.handshake_timeout_id is not None:
            try:
                self.root.after_cancel(self.handshake_timeout_id)
            except tk.TclError:
                pass
            self.handshake_timeout_id = None
        self.serial_controller.close()
        self.connected = False
        self.connecting = False
        self.calibrated = False
        self.current_position = None
        self.motion_state = "IDLE"
        self._clear_jog_hold()
        self.jog_stop_pending = False
        self.connection_var.set("DISCONNECTED")
        self.connection_label.configure(style="Muted.TLabel")
        self.calibration_var.set("UNCALIBRATED")
        self.calibration_label.configure(style="Warning.TLabel")
        self.position_var.set("UNCALIBRATED")
        self.motion_var.set("IDLE")
        self.motion_status_label.configure(style="Value.TLabel")
        self.target_var.set("--")
        self._log(reason)
        self._update_controls()

    def _parse_number(self, text: str, label: str, minimum: float, maximum: float) -> Optional[float]:
        try:
            value = float(text.strip())
        except (ValueError, TypeError):
            messagebox.showwarning("Invalid Input", f"{label} must be a valid number.")
            return None
        if not math.isfinite(value) or value < minimum or value > maximum:
            messagebox.showwarning(
                "Input Out of Range", f"{label} must be between {minimum:g} and {maximum:g}."
            )
            return None
        return value

    def _validated_parameters(self):
        speed = self._parse_number(
            self.speed_var.get(), "Speed", MIN_SPEED_MM_S, MAX_SPEED_MM_S
        )
        if speed is None:
            return None
        acceleration = self._parse_number(
            self.accel_var.get(), "Acceleration", MIN_ACCEL_MM_S2, MAX_ACCEL_MM_S2
        )
        if acceleration is None:
            return None
        return speed, acceleration

    def _apply_parameters(self, quiet: bool = False) -> bool:
        if not self.connected:
            if not quiet:
                messagebox.showwarning("Not Connected", "Connect to the Arduino first.")
            return False
        parameters = self._validated_parameters()
        if parameters is None:
            return False
        speed, acceleration = parameters
        self._send_command(f"SET SPEED {speed:.3f}")
        self._send_command(f"SET ACCEL {acceleration:.3f}")
        self.commanded_speed_var.set(f"{speed:.2f} mm/s")
        return True

    def _start_jog(self, direction: str, button=None) -> None:
        # After the previous Jog is released, STOPPED/IDLE may not have arrived yet.
        # Allow an immediate opposite-direction hold; serial FIFO preserves the
        # STOP -> SET -> JOG command order.
        ready_for_jog = self.motion_state == "IDLE" or self.jog_stop_pending
        if not self.connected or not ready_for_jog or self.jog_held:
            return
        if not self._apply_parameters(quiet=True):
            return

        # Keep mouse-hold state independent so a delayed Arduino IDLE cannot clear it.
        self.jog_held = True
        self.jog_direction = direction
        self.jog_button = button
        self.jog_stop_pending = False
        if button is not None:
            try:
                # Keep ButtonRelease routed to this application if the pointer leaves.
                button.grab_set()
            except tk.TclError:
                pass

        if not self._send_command(f"JOG {direction}"):
            self._clear_jog_hold()
            self.jog_stop_pending = False
            return
        self._update_controls()

    def _clear_jog_hold(self) -> None:
        """Clear GUI hold state and mouse capture without sending a command."""
        captured_button = self.jog_button
        self.jog_held = False
        self.jog_direction = None
        self.jog_button = None
        if captured_button is not None:
            try:
                captured_button.grab_release()
            except tk.TclError:
                pass

    def _stop_jog(self, _event=None) -> None:
        if self.jog_held:
            self._send_stop()

    def _global_button_release(self, _event=None) -> None:
        # Releasing after the pointer leaves a Jog button must still issue STOP.
        if self.jog_held:
            self._stop_jog()

    def _on_focus_out(self, _event=None) -> None:
        # Tk's Toplevel bind tag also receives FocusOut between child controls.
        # Handle only the main window leaving the focus hierarchy; otherwise an
        # internal Forward-to-Reverse focus change would issue a false STOP.
        if not self.jog_held:
            return
        if _event is not None and _event.widget is not self.root:
            return
        self.root.after_idle(self._stop_jog_if_window_inactive)

    def _stop_jog_if_window_inactive(self) -> None:
        if not self.jog_held or self.closing:
            return
        try:
            focused_widget = self.root.focus_displayof()
            main_window_still_active = (
                focused_widget is not None
                and focused_widget.winfo_toplevel() == self.root
            )
        except tk.TclError:
            main_window_still_active = False
        if not main_window_still_active:
            self._stop_jog()

    def _send_stop(self) -> None:
        # STOP never waits for an ACK or displayed state; send it whenever the port is open.
        was_jogging = self.jog_held or self.motion_state in {"JOG_FWD", "JOG_REV"}
        self._clear_jog_hold()
        self.jog_stop_pending = was_jogging
        if self.serial_controller.is_open:
            if not self._send_command("STOP"):
                self.jog_stop_pending = False
        else:
            self.jog_stop_pending = False
        self._update_controls()

    def _move(self, direction: int) -> None:
        if not self.connected:
            messagebox.showwarning("Not Connected", "Connect to the Arduino first.")
            return
        if not self.calibrated or self.current_position is None:
            messagebox.showwarning(
                "Not Zeroed", "Jog to the mechanical zero and set the current position to 0 first."
            )
            return
        try:
            distance = float(self.distance_var.get().strip())
        except ValueError:
            messagebox.showwarning("Invalid Input", "Distance must be a valid number.")
            return
        if not math.isfinite(distance) or distance <= 0.0:
            messagebox.showwarning(
                "Invalid Input",
                "Enter a positive distance and select direction with the Forward or Reverse button.",
            )
            return
        target = self.current_position + direction * distance
        epsilon = 1e-6
        if target < MIN_POSITION_MM - epsilon or target > MAX_POSITION_MM + epsilon:
            boundary = MIN_POSITION_MM if target < MIN_POSITION_MM else MAX_POSITION_MM
            messagebox.showwarning(
                "Software Limit Exceeded",
                f"Target position {target:.2f} mm exceeds the {boundary:.2f} mm software limit.\nThe MOVE command was not sent.",
            )
            return
        if not self._apply_parameters(quiet=True):
            return
        signed_distance = direction * distance
        self.target_var.set(f"{target:.3f} mm")
        self._send_command(f"MOVE {signed_distance:+.3f}")

    def _set_zero(self) -> None:
        if not self.connected or self.motion_state != "IDLE":
            return
        confirmed = messagebox.askyesno(
            "Confirm Mechanical Zero",
            "Confirm that the stage is at the end farthest from the front catheter drive motor.\n\n"
            "Set the current position to 0.00 mm?",
            icon="warning",
        )
        if confirmed:
            self._send_command("ZERO")

    def _heartbeat(self) -> None:
        if not self.closing:
            if self.connected and self.serial_controller.is_open:
                self._send_command("HB", log=False)
            self.root.after(HEARTBEAT_MS, self._heartbeat)

    def _process_events(self) -> None:
        try:
            while True:
                event, payload = self.events.get_nowait()
                if event == "PORT_OPEN":
                    self._log(f"Port opened: {payload}; waiting for Arduino UNO reset")
                    # Opening an UNO port often triggers reset; wait 2 seconds asynchronously.
                    self.root.after(2000, self._begin_handshake)
                elif event == "OPEN_ERROR":
                    self.connecting = False
                    self.connection_var.set("DISCONNECTED")
                    self.connection_label.configure(style="Muted.TLabel")
                    self._log(f"Failed to open serial port: {payload}")
                    messagebox.showerror("Serial Connection Failed", payload)
                    self._update_controls()
                elif event == "LINE":
                    self._handle_line(payload)
                elif event == "CONNECTION_LOST":
                    self._log(f"Serial connection lost: {payload}")
                    if not self.closing:
                        messagebox.showerror(
                            "Serial Port Disconnected",
                            "The Arduino connection was lost. The Arduino will stop motion after the approximately 1-second heartbeat timeout.",
                        )
                    self._finish_disconnect("Serial port disconnected unexpectedly")
        except queue.Empty:
            pass
        if not self.closing:
            self.root.after(50, self._process_events)

    def _handle_line(self, line: str) -> None:
        # High-rate STATUS lines refresh the UI but are not logged individually.
        if not line.startswith("STATUS "):
            self._log(f"RX: {line}")

        if line == "READY":
            # READY means the Arduino just reset, so the old software position is invalid.
            self._clear_jog_hold()
            self.jog_stop_pending = False
            self.calibrated = False
            self.current_position = None
            self.motion_state = "IDLE"
            self.calibration_var.set("UNCALIBRATED")
            self.calibration_label.configure(style="Warning.TLabel")
            self.position_var.set("UNCALIBRATED")
            self.motion_var.set("IDLE")
            self.motion_status_label.configure(style="Value.TLabel")
            self.target_var.set("--")
        elif line == "PONG":
            if self.handshake_timeout_id is not None:
                try:
                    self.root.after_cancel(self.handshake_timeout_id)
                except tk.TclError:
                    pass
                self.handshake_timeout_id = None
            self.connected = True
            self.connecting = False
            self.connection_var.set("● CONNECTED")
            self.connection_label.configure(style="Connected.TLabel")
            self._send_command("GET STATUS")
        elif line.startswith("STATUS "):
            self._parse_status(line)
        elif line.startswith("POS "):
            self._parse_position(line[4:])
        elif line.startswith("STATE "):
            self._set_motion_state(line[6:])
        elif line.startswith("TARGET "):
            value = line[7:]
            self.target_var.set("--" if value == "--" else f"{value} mm")
        elif line.startswith("ACK SPEED "):
            try:
                value = float(line.split()[2])
                self.commanded_speed_var.set(f"{value:.2f} mm/s")
            except (ValueError, IndexError):
                pass
        elif line == "ACK ZERO":
            self.calibrated = True
            self.current_position = 0.0
            self.calibration_var.set("ZEROED")
            self.calibration_label.configure(style="Connected.TLabel")
            self.position_var.set("0.000 mm")
        elif line == "DONE":
            self.motion_var.set("DONE")
            self.motion_status_label.configure(style="Connected.TLabel")
        elif line == "STOPPED":
            # If a new direction is held, this belongs to the previous STOP and
            # must not clear the new hold state.
            if not self.jog_held:
                self._clear_jog_hold()
                self.jog_stop_pending = False
                self.motion_var.set("STOPPED")
                self.motion_status_label.configure(style="Danger.TLabel")
        elif line.startswith("LIMIT "):
            self._clear_jog_hold()
            self.jog_stop_pending = False
            self.motion_state = "IDLE"
            self.motion_var.set(line)
            self.motion_status_label.configure(style="Warning.TLabel")
            messagebox.showwarning("Software Limit Reached", f"Arduino reported: {line}")
        elif line.startswith("ERR "):
            self._clear_jog_hold()
            self.jog_stop_pending = False
            self.motion_var.set("ERROR")
            self.motion_status_label.configure(style="Danger.TLabel")
            if line == "ERR NOT_ZEROED":
                self.calibrated = False
                self.current_position = None
                self.calibration_var.set("UNCALIBRATED")
                self.calibration_label.configure(style="Warning.TLabel")
                self.position_var.set("UNCALIBRATED")
            error_messages = {
                "ERR NOT_ZEROED": "Arduino rejected MOVE because the stage is not zeroed.",
                "ERR OUT_OF_RANGE": "Arduino rejected the command because the target exceeds the 0-280 mm software range.",
                "ERR INVALID_COMMAND": "Arduino did not recognize the command.",
                "ERR INVALID_PARAMETER": "Arduino rejected an invalid parameter.",
                "ERR LINK_TIMEOUT": "Communication heartbeat timed out; Arduino stopped motion.",
                "ERR BUSY": "Arduino is moving, so the command was rejected.",
                "ERR LINE_TOO_LONG": "The serial command was too long and Arduino discarded the line.",
            }
            messagebox.showerror("Arduino Error", error_messages.get(line, line))

        self._update_controls()

    def _parse_status(self, line: str) -> None:
        parts = line.split()
        if len(parts) != 4:
            return
        _, state, position, target = parts
        self._set_motion_state(state)
        self._parse_position(position)
        self.target_var.set("--" if target == "-" else f"{target} mm")

    def _parse_position(self, value: str) -> None:
        if value == "UNCALIBRATED":
            self.calibrated = False
            self.current_position = None
            self.calibration_var.set("UNCALIBRATED")
            self.calibration_label.configure(style="Warning.TLabel")
            self.position_var.set("UNCALIBRATED")
            return
        try:
            position = float(value)
        except ValueError:
            return
        self.calibrated = True
        self.current_position = position
        self.calibration_var.set("ZEROED")
        self.calibration_label.configure(style="Connected.TLabel")
        self.position_var.set(f"{position:.3f} mm")

    def _set_motion_state(self, state: str) -> None:
        self.motion_state = state
        labels = {
            "IDLE": "IDLE",
            "JOG_FWD": "JOG FORWARD",
            "JOG_REV": "JOG REVERSE",
            "MOVE": "MOVING",
        }
        self.motion_var.set(labels.get(state, state))
        if state in {"JOG_FWD", "JOG_REV", "MOVE"}:
            self.motion_status_label.configure(style="Active.TLabel")
        else:
            self.motion_status_label.configure(style="Value.TLabel")
        if state == "IDLE" and not self.jog_held:
            self.jog_stop_pending = False
    def _update_controls(self) -> None:
        port_open = self.serial_controller.is_open
        idle = self.motion_state == "IDLE"
        connected_idle = self.connected and idle

        self.connect_button.configure(
            state="disabled" if self.connecting or port_open else "normal"
        )
        self.disconnect_button.configure(state="normal" if port_open else "disabled")
        self.refresh_button.configure(state="disabled" if port_open else "normal")
        self.auto_button.configure(state="disabled" if port_open else "normal")
        self.port_combo.configure(state="disabled" if port_open else "readonly")

        if self.connected and self.jog_held:
            # Keep both buttons enabled to avoid a false FocusOut when a previously
            # focused button is disabled. Mouse grab and jog_held prevent a second Jog.
            forward_state = "normal"
            reverse_state = "normal"
        else:
            jog_ready = self.connected and (idle or self.jog_stop_pending)
            forward_state = "normal" if jog_ready else "disabled"
            reverse_state = "normal" if jog_ready else "disabled"
        self.jog_forward_button.configure(state=forward_state)
        self.jog_reverse_button.configure(state=reverse_state)
        self.stop_button.configure(state="normal" if self.connected else "disabled")
        self.zero_button.configure(state="normal" if connected_idle else "disabled")
        self.apply_button.configure(state="normal" if connected_idle else "disabled")

        move_enabled = connected_idle and self.calibrated
        move_state = "normal" if move_enabled else "disabled"
        self.move_forward_button.configure(state=move_state)
        self.move_reverse_button.configure(state=move_state)
        for button in self.preset_buttons:
            button.configure(state=move_state)
        self.distance_entry.configure(state=move_state)
        parameter_state = "normal" if connected_idle else "disabled"
        self.speed_entry.configure(state=parameter_state)
        self.accel_entry.configure(state=parameter_state)

    def _on_close(self) -> None:
        if self.closing:
            return
        self.closing = True
        self._clear_jog_hold()
        if self.serial_controller.is_open:
            self._send_command("STOP")
            self.root.after(150, self._close_now)
        else:
            self._close_now()

    def _close_now(self) -> None:
        self.serial_controller.close()
        self.root.destroy()


def main() -> None:
    root = tk.Tk()
    LinearStageGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
